module.exports = {
  searchelectricitybills: "srq.search_electricity_bills",
  getelectricitybills: "srq.get_electricity_bills",
  saveelectricitybills: "srq.save_electricity_bills",
  deleteelectricitybills: "srq.delete_electricity_bills",
  searchebbilldocverifications: "sdoc.search_eb_bill_doc_verifications",
  getebbilldocverifications: "sdoc.get_eb_bill_doc_verifications",
  saveebbilldocverifications: "sdoc.save_eb_bill_doc_verifications",
  searchebbillrequestupdations: "sdoc.search_eb_bill_request_updations",
  getebbillrequestupdations: "sdoc.get_eb_bill_request_updations",
  saveebbillrequestupdations: "sdoc.save_eb_bill_request_updations",
  getmailebbillrequests: "sdoc.get_mail_eb_bill_request",
  savemailebbillrequests: "sdoc.save_mail_eb_bill_request",
  searchbulkpayments: "spay.search_bulk_payments",
  mailelectricitybill: "alert.mail_electricity_bill_request",
  getservicecharges:"com.get_service_charges",
};
